/* Source: /Users/amirkhabaza/JacHacks2026/components/ByllmSection.jac */
import {__jacJsx, __jacSpawn} from "@jac/runtime";
import { Sparkles, ArrowRight } from "lucide-react";
import { Card, CardContent } from "./ui/card.js";
import { Badge } from "./ui/badge.js";
import { CodeBlock } from "./CodeBlock.js";
import { SectionShell } from "./SectionShell.js";
let _CODE = "import from byllm { Model }\n\nglob llm = Model(model_name=\"gpt-4o\");\n\nenum Priority { LOW, MEDIUM, HIGH, URGENT }\n\nobj Ticket {\n    has summary: str,\n        priority: Priority,\n        tags: list[str];\n}\n\n# No prompt string. The signature is the contract; byLLM\n# fills the body and returns a typed, validated Ticket.\ndef triage(message: str) -> Ticket by llm();";
function ByllmSection() {
  return __jacJsx(SectionShell, {"id": "ai", "eyebrow": "AI-native", "title": "Functions powered by an LLM", "subtitle": "Write the signature, write `by llm()`, and the model becomes the implementation - returning typed, validated objects, not loose text. Nothing to run here because tokens cost $$$ (for now ;-) :-) :-))."}, [__jacJsx("div", {"className": "grid items-center gap-8 lg:grid-cols-2"}, [__jacJsx(CodeBlock, {"code": _CODE, "filename": "triage.jac"}, []), __jacJsx(Card, {"className": "border-border bg-card/60"}, [__jacJsx(CardContent, {"className": "flex flex-col gap-4 p-6"}, [__jacJsx("div", {"className": "flex items-center gap-2 text-sm text-muted-foreground"}, [__jacJsx(Sparkles, {"size": 15, "className": "text-primary"}, []), "triage(message) call"]), __jacJsx("div", {"className": "rounded-lg border border-border bg-background/60 p-4 font-mono text-sm text-foreground"}, ["\"the checkout page 500s every time I hit pay, losing sales right now!!\""]), __jacJsx("div", {"className": "flex justify-center text-muted-foreground"}, [__jacJsx(ArrowRight, {"size": 18, "className": "rotate-90"}, [])]), __jacJsx("div", {"className": "flex flex-col gap-3 rounded-lg border border-primary/30 bg-primary/5 p-4"}, [__jacJsx("div", {"className": "flex items-center justify-between"}, [__jacJsx("span", {"className": "font-mono text-xs text-muted-foreground"}, ["Ticket"]), __jacJsx(Badge, {"className": "bg-destructive/15 text-destructive"}, ["URGENT"])]), __jacJsx("div", {"className": "font-mono text-sm"}, [__jacJsx("span", {"className": "text-muted-foreground"}, ["summary: "]), __jacJsx("span", {"className": "text-foreground"}, ["\"Checkout returns 500 on payment\""])]), __jacJsx("div", {"className": "flex flex-wrap items-center gap-2 font-mono text-sm"}, [__jacJsx("span", {"className": "text-muted-foreground"}, ["tags:"]), ["checkout", "payments", "regression"].map(t => __jacJsx(Badge, {"variant": "secondary", "key": t, "className": "font-normal"}, [t]))])])])])])]);
}
/*jac:refresh-boundary*/;
export {ByllmSection};
//# sourceMappingURL=ByllmSection.js.map
