/* Source: /Users/amirkhabaza/JacHacks2026/components/LittleXSection.jac */
import {__jacJsx, __jacSpawn} from "@jac/runtime";
import { AppWindow, ArrowUpRight } from "lucide-react";
import { Link } from "@jac/runtime";
import { SectionShell } from "./SectionShell.js";
import { CodeBlock } from "./CodeBlock.js";
import { DocsView } from "./DocsView.js";
import { app as LittleX } from "../littlex/frontend.js";
function LittleXSection() {
  let app_code = "# app.jac - the data, the endpoint, and the UI in one file.\n\n# this is a class\nnode Tweet {\n    has content: str,\n        author: str,\n        likes: int = 0;\n}\n\n# Back end: compiles to a public endpoint - this IS the API.\ndef:pub create_tweet(content: str) -> Tweet {\n    # this might look strange, but it abstracts away auth and db\n    root ++> (tweet := Tweet(content=content, author=\"ada\"));\n    return tweet;\n}\n\n# Front end: a cl def calls the endpoint like a function.\ncl def Composer -> JsxElement {\n    has text: str = \"\";\n\n    async def post -> None {\n        new_tweet = await create_tweet(text);  # typed end to end\n        print(new_tweet.author, new_tweet.likes);\n    }\n\n    return <button onClick={post}>Tweet</button>;\n}";
  return __jacJsx(SectionShell, {"id": "littlex", "eyebrow": "Real apps", "title": "Below is a Real Twitter-like App. Use It.", "subtitle": "In a single component. All frontend/backend interfacing, data handling, and db organization is abstracted away (done for you and optimized by the compiler)."}, [__jacJsx("div", {"className": "mx-auto max-w-5xl"}, [__jacJsx("div", {"className": "overflow-hidden rounded-2xl border border-border bg-card shadow-2xl shadow-black/40"}, [__jacJsx("div", {"className": "flex items-center gap-2 border-b border-border/70 bg-white/[0.02] px-4 py-2.5"}, [__jacJsx("span", {"className": "size-3 rounded-full bg-[#ff5f57]"}, []), __jacJsx("span", {"className": "size-3 rounded-full bg-[#febc2e]"}, []), __jacJsx("span", {"className": "size-3 rounded-full bg-[#28c840]"}, []), __jacJsx("span", {"className": "ml-2 flex items-center gap-1.5 font-mono text-xs text-muted-foreground"}, [__jacJsx(AppWindow, {"size": 13}, []), "littlex - embedded live app, same graph"]), __jacJsx(Link, {"to": "/littlex", "className": "ml-auto flex items-center gap-1 rounded-md px-2 py-1 text-xs text-muted-foreground transition hover:bg-white/5 hover:text-foreground"}, ["open full app", __jacJsx(ArrowUpRight, {"size": 13}, [])])]), __jacJsx("div", {"className": "h-[78vh] min-h-[600px] max-h-[860px] overflow-hidden bg-background"}, [__jacJsx(LittleX, {}, [])])]), __jacJsx("p", {"className": "mt-4 text-center text-sm text-muted-foreground"}, ["Sign up inside the frame to try it - your account and posts persist in the shared graph. Or", " ", __jacJsx(Link, {"to": "/littlex", "className": "font-medium text-primary hover:underline"}, ["open the full app at /littlex"]), "."]), __jacJsx("div", {"className": "mb-10"}, [__jacJsx("p", {"className": "mb-4 text-center text-sm text-muted-foreground"}, ["The data, the endpoint, and the UI in one file: the front end calls the back end like a function and gets a typed", " ", __jacJsx("span", {"className": "font-mono text-foreground"}, ["Tweet"]), " ", "back. No fetch, no REST route, no JSON."]), __jacJsx("div", {"className": "grid items-stretch gap-4 lg:grid-cols-2"}, [__jacJsx(CodeBlock, {"filename": "app.jac", "code": app_code, "dense": true}, []), __jacJsx(DocsView, {}, [])]), __jacJsx("p", {"className": "mt-3 text-center text-xs text-muted-foreground"}, ["That single file is already a live API: every endpoint shows up in the auto-generated Swagger UI on the right."])])])]);
}
/*jac:refresh-boundary*/;
export {LittleXSection};
//# sourceMappingURL=LittleXSection.js.map
