/* Source: /Users/amirkhabaza/JacHacks2026/components/OutroSection.jac */
import {__jacJsx, __jacSpawn} from "@jac/runtime";
import { Terminal, BookOpen, Github, ArrowUpRight } from "lucide-react";
import { Button } from "./ui/button.js";
function OutroSection() {
  return __jacJsx("section", {"className": "relative flex min-h-screen flex-col justify-center overflow-hidden px-6 py-32"}, [__jacJsx("div", {"className": "tij-glow absolute inset-x-0 bottom-0 -z-10 h-[400px] rotate-180"}, []), __jacJsx("div", {"className": "mx-auto flex max-w-3xl flex-col items-center text-center"}, [__jacJsx("h2", {"className": "font-display text-4xl font-bold tracking-tight text-foreground md:text-5xl"}, ["Build anything in", " ", __jacJsx("span", {"className": "tij-gradient-text"}, ["one language"]), "."]), __jacJsx("p", {"className": "mt-4 max-w-xl text-lg text-muted-foreground"}, ["The graph, the API, the UI, and the native core - no glue, no context-switching, no second runtime."]), __jacJsx("div", {"className": "mt-8 flex items-center gap-3 rounded-full border border-border bg-card/60 px-5 py-3 font-mono text-base text-foreground backdrop-blur"}, [__jacJsx(Terminal, {"size": 18, "className": "text-primary"}, []), "pip install jaclang"]), __jacJsx("div", {"className": "mt-8 flex flex-wrap items-center justify-center gap-3"}, [__jacJsx("a", {"href": "https://www.jac-lang.org", "target": "_blank", "rel": "noreferrer"}, [__jacJsx(Button, {"size": "lg", "className": "rounded-full px-6 font-semibold"}, [__jacJsx(BookOpen, {"size": 18}, []), "Read the docs", __jacJsx(ArrowUpRight, {"size": 16}, [])])]), __jacJsx("a", {"href": "https://github.com/jaseci-labs/jaseci", "target": "_blank", "rel": "noreferrer"}, [__jacJsx(Button, {"size": "lg", "variant": "outline", "className": "rounded-full px-6 font-semibold"}, [__jacJsx(Github, {"size": 18}, []), "Star on GitHub"])])]), __jacJsx("div", {"className": "mt-20 flex flex-col items-center gap-1 text-sm text-muted-foreground"}, [__jacJsx("div", {"className": "flex items-center gap-2 font-display font-bold text-foreground"}, [__jacJsx("span", {"className": "flex size-6 items-center justify-center rounded-md bg-primary font-mono text-xs text-primary-foreground"}, ["J"]), "this is jac"]), __jacJsx("span", {}, ["Built end-to-end in Jac. Every demo on this page is real."])])])]);
}
/*jac:refresh-boundary*/;
export {OutroSection};
//# sourceMappingURL=OutroSection.js.map
